// src/index.ts
import { loadConfig } from './config';
import { shouldReview, getTriggerAction } from './triggers';
import { fetchPRContext } from './github/diff';
import { postReview } from './github/review';
import { postComment } from './github/comment';
import { createProvider } from './llm/provider';
import { loadContext, generateContextPrompt } from './context';
import { walkTree, readKeyFiles, readChangedFiles } from './github/files';
import { ReviewComment } from './types';
import fs from 'fs';
import path from 'path';

async function main(): Promise<void> {
  const eventPath = process.env.GITHUB_EVENT_PATH;
  const token = process.env.GITHUB_TOKEN;
  const repoPath = process.env.GITHUB_WORKSPACE ?? '.';

  if (!eventPath || !token) {
    console.error('Missing GITHUB_EVENT_PATH or GITHUB_TOKEN');
    process.exit(0);
  }

  const event = JSON.parse(fs.readFileSync(eventPath, 'utf-8'));
  const eventName = process.env.GITHUB_EVENT_NAME ?? '';

  const config = loadConfig(repoPath);

  if (!shouldReview(config, eventName, event.comment ?? { body: '' })) {
    console.log('No trigger matched. Skipping review.');
    process.exit(0);
  }

  const repo = event.repository?.name;
  const owner = event.repository?.owner?.login;
  const pullNumber =
    event.pull_request?.number ??
    event.issue?.number;

  if (!repo || !owner || !pullNumber) {
    console.error('Could not determine repo, owner, or PR number from event');
    process.exit(0);
  }

  const action = eventName === 'issue_comment'
    ? getTriggerAction(event.comment ?? { body: '' })
    : 'review';

  try {
    if (action === 'generate-context') {
      await handleGenerateContext(token, owner, repo, pullNumber, repoPath, config);
      process.exit(0);
    }

    await handleReview(token, owner, repo, pullNumber, repoPath, config, event);
  } catch (err) {
    console.error('Review failed:', err instanceof Error ? err.message : String(err));
    process.exit(0);
  }
}

async function handleGenerateContext(
  token: string,
  owner: string,
  repo: string,
  pullNumber: number,
  repoPath: string,
  config: ReturnType<typeof loadConfig>
): Promise<void> {
  console.log('Generating project context...');

  const tree = walkTree(repoPath);
  const keyFiles = readKeyFiles(repoPath);

  const provider = createProvider(config.llm);
  const prompt = generateContextPrompt(tree, keyFiles);

  const result = await provider.review({
    diff: '',
    files: [],
    pr: { title: 'Generate Context', description: 'Analyze project and generate context file' },
    config: config.llm,
  });

  // Write the generated context to the file
  const contextFile = config.context?.file ?? 'CLAUDE.md';
  const contextPath = path.join(repoPath, contextFile);
  fs.writeFileSync(contextPath, `<!-- Generated by PR Review Bot -->\n\n${result.summary}`);

  await postComment(
    token, owner, repo, pullNumber,
    `I've generated a project context file at \`${contextFile}\`. ` +
    `Please review it and commit it to the repository. ` +
    `I'll use this file to provide better PR reviews.\n\n` +
    `> Tip: You can update \`${contextFile}\` at any time to improve review quality.`
  );

  console.log(`Context file written to ${contextFile}`);
}

async function handleReview(
  token: string,
  owner: string,
  repo: string,
  pullNumber: number,
  repoPath: string,
  config: ReturnType<typeof loadConfig>,
  event: Record<string, unknown>
): Promise<void> {
  // Load project context
  const contextResult = loadContext(repoPath, config);

  // Check if this is a first PR and no context file exists
  if (!contextResult.exists && event.pull_request) {
    const eventAction = (event as { action?: string }).action;
    if (eventAction === 'opened') {
      await postComment(
        token, owner, repo, pullNumber,
        `Hi! I'm the PR Review Bot. I noticed this repo doesn't have a project context file (\`${contextResult.filename}\`).\n\n` +
        `A context file helps me understand your project's architecture, conventions, and guidelines, leading to much better code reviews.\n\n` +
        `**Reply with \`/review generate-context\`** and I'll analyze your entire project and generate one for you. ` +
        `You can then review and customize it.\n\n` +
        `> You can also create \`${contextResult.filename}\` manually at any time.`
      );
    }
  }

  console.log(`Reviewing PR #${pullNumber} in ${owner}/${repo} using ${config.llm.provider}`);

  const { diff, files, pr } = await fetchPRContext(token, owner, repo, pullNumber);

  if (!diff.trim()) {
    console.log('Empty diff. Skipping review.');
    process.exit(0);
  }

  const maxFiles = config.limits?.max_files ?? 20;
  const maxLines = config.limits?.max_lines_per_file ?? 500;

  let truncatedFiles = files.slice(0, maxFiles).map((f) => ({
    ...f,
    patch: f.patch
      ?.split('\n')
      .slice(0, maxLines)
      .join('\n'),
  }));

  let truncated = files.length > maxFiles;

  // Read full file contents for changed files (better context for LLM)
  const changedFilenames = truncatedFiles.map((f) => f.filename);
  const fullFileContents = readChangedFiles(repoPath, changedFilenames);

  const truncatedDiff = truncatedFiles
    .map((f) => `--- a/${f.filename}\n+++ b/${f.filename}\n${f.patch ?? ''}`)
    .join('\n');

  // Combine diff with full file contents for richer context
  const enhancedDiff = truncatedDiff + '\n\n## Full File Contents (for context)\n\n' + fullFileContents;

  const provider = createProvider(config.llm);
  const result = await provider.review({
    diff: enhancedDiff,
    files: truncatedFiles,
    pr,
    config: config.llm,
    context: contextResult.content,
  });

  let summary = result.summary;
  if (truncated) {
    summary += `\n\n_(Review truncated: only first ${maxFiles} files were reviewed.)_`;
  }
  if (contextResult.exists) {
    summary += `\n\n_(Review enhanced with project context from \`${contextResult.filename}\`.)_`;
  }

  const headSha = (event as { pull_request?: { head?: { sha?: string } } }).pull_request?.head?.sha;
  if (headSha) {
    await postReview(token, owner, repo, pullNumber, headSha, {
      ...result,
      summary,
    });
    console.log(`Review posted: ${result.comments.length} comments`);
  }
}

main();
