// src/index.ts
import { loadConfig } from './config';
import { shouldReview, shouldUpdateContext, getTriggerAction } from './triggers';
import { fetchPRContext } from './github/diff';
import { postReview } from './github/review';
import { postComment } from './github/comment';
import { createProvider } from './llm/provider';
import { loadContext, generateContextPrompt, generateMergeUpdatePrompt, appendMergeUpdateToContext } from './context';
import { walkTree, readKeyFiles, readChangedFiles } from './github/files';
import { getCommitHistory, formatCommitHistory, getMostChangedFiles } from './github/commits';
import { ReviewComment } from './types';
import Anthropic from '@anthropic-ai/sdk';
import OpenAI from 'openai';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

async function main(): Promise<void> {
  const eventPath = process.env.GITHUB_EVENT_PATH;
  const token = process.env.GITHUB_TOKEN;
  const repoPath = process.env.GITHUB_WORKSPACE ?? '.';

  if (!eventPath || !token) {
    console.error('Missing GITHUB_EVENT_PATH or GITHUB_TOKEN');
    process.exit(0);
  }

  const event = JSON.parse(fs.readFileSync(eventPath, 'utf-8'));
  const eventName = process.env.GITHUB_EVENT_NAME ?? '';

  const config = loadConfig(repoPath);

  const repo = event.repository?.name;
  const owner = event.repository?.owner?.login;
  const pullNumber =
    event.pull_request?.number ??
    event.issue?.number;

  if (!repo || !owner || !pullNumber) {
    console.error('Could not determine repo, owner, or PR number from event');
    process.exit(0);
  }

  try {
    // Check for merge event first (before review trigger)
    if (shouldUpdateContext(config, eventName, event)) {
      await handleMergeContextUpdate(token, owner, repo, pullNumber, repoPath, config, event);
      process.exit(0);
    }

    if (!shouldReview(config, eventName, event.comment ?? { body: '' })) {
      console.log('No trigger matched. Skipping review.');
      process.exit(0);
    }

    const action = eventName === 'issue_comment'
      ? getTriggerAction(event.comment ?? { body: '' })
      : 'review';

    if (action === 'generate-context') {
      await handleGenerateContext(token, owner, repo, pullNumber, repoPath, config);
      process.exit(0);
    }

    await handleReview(token, owner, repo, pullNumber, repoPath, config, event);
  } catch (err) {
    console.error('Review failed:', err instanceof Error ? err.message : String(err));
    process.exit(0);
  }
}

async function handleGenerateContext(
  token: string,
  owner: string,
  repo: string,
  pullNumber: number,
  repoPath: string,
  config: ReturnType<typeof loadConfig>
): Promise<void> {
  console.log('Generating project context with full history...');

  const tree = walkTree(repoPath);
  const keyFiles = readKeyFiles(repoPath);
  const commits = getCommitHistory(repoPath);
  const commitHistory = formatCommitHistory(commits);
  const hotFiles = getMostChangedFiles(commits);

  // Read source files that are most frequently changed (up to 2000 chars each)
  const sourceFiles: Record<string, string> = {};
  for (const filepath of hotFiles) {
    const fullPath = path.join(repoPath, filepath);
    if (fs.existsSync(fullPath)) {
      try {
        const content = fs.readFileSync(fullPath, 'utf-8');
        sourceFiles[filepath] = content;
      } catch {
        // skip binary/unreadable
      }
    }
  }

  const prompt = generateContextPrompt(tree, keyFiles, commitHistory, sourceFiles);
  const contextContent = await callLLMRaw(config, prompt);

  const contextFile = config.context?.file ?? 'CONTEXT.md';
  const contextPath = path.join(repoPath, contextFile);
  fs.writeFileSync(contextPath, `<!-- Generated by PatchFox -->\n\n${contextContent}`);

  await postComment(
    token, owner, repo, pullNumber,
    `I've analyzed the project's commit history (${commits.length} commits) and source files to generate \`${contextFile}\`.\n\n` +
    `Please review it, make any adjustments, and commit it to the repository. ` +
    `I'll use this file to provide better PR reviews.\n\n` +
    `> Tip: Update \`${contextFile}\` at any time to refine my understanding of your project.`
  );

  console.log(`Context file written to ${contextFile} with ${commits.length} commits analyzed`);
}

async function handleMergeContextUpdate(
  token: string,
  owner: string,
  repo: string,
  pullNumber: number,
  repoPath: string,
  config: ReturnType<typeof loadConfig>,
  event: Record<string, unknown>
): Promise<void> {
  console.log(`PR #${pullNumber} merged. Updating project context...`);

  const contextResult = loadContext(repoPath, config);
  const contextFilename = config.context?.file ?? 'CONTEXT.md';

  if (!contextResult.exists) {
    console.log(`No ${contextFilename} found. Skipping merge context update.`);
    await postComment(
      token, owner, repo, pullNumber,
      `PR #${pullNumber} was merged. I'd like to update the project context, ` +
      `but there is currently no \`${contextFilename}\` file. ` +
      `Use \`/review generate-context\` to create one, and I'll automatically ` +
      `update it on future merges.`
    );
    return;
  }

  const { diff, files, pr } = await fetchPRContext(token, owner, repo, pullNumber);

  if (!diff.trim()) {
    console.log('Empty diff on merged PR. Skipping context update.');
    return;
  }

  const prompt = generateMergeUpdatePrompt({
    currentContext: contextResult.content!,
    prNumber: pullNumber,
    prTitle: pr.title,
    prDescription: pr.description,
    diff,
    changedFiles: files.map((f) => `${f.filename} (+${f.additions}/-${f.deletions})`),
  });

  const updateContent = await callLLMRaw(config, prompt);

  const contextPath = path.join(repoPath, contextFilename);
  const updatedContent = appendMergeUpdateToContext(contextResult.content!, updateContent);
  fs.writeFileSync(contextPath, updatedContent);

  const baseRef = ((event as any).pull_request?.base?.ref as string) ?? 'main';

  try {
    execSync(`git config user.name "patchfox[bot]"`, { cwd: repoPath });
    execSync(`git config user.email "patchfox[bot]@users.noreply.github.com"`, { cwd: repoPath });
    execSync(`git add "${contextFilename}"`, { cwd: repoPath });
    execSync(`git commit -m "docs: update ${contextFilename} after PR #${pullNumber}"`, { cwd: repoPath });
    execSync(`git push origin HEAD:${baseRef}`, { cwd: repoPath });
  } catch (gitErr) {
    console.error('Failed to commit/push context update:', gitErr instanceof Error ? gitErr.message : String(gitErr));
  }

  await postComment(
    token, owner, repo, pullNumber,
    `PR #${pullNumber} was merged. I've updated \`${contextFilename}\` to reflect the changes.\n\n` +
    `**What changed:**\n${updateContent.trim()}\n\n` +
    `_The \`${contextFilename}\` file on \`${baseRef}\` has been updated with this entry._`
  );

  console.log(`Context updated for merged PR #${pullNumber}`);
}

async function callLLMRaw(
  config: ReturnType<typeof loadConfig>,
  prompt: string
): Promise<string> {
  if (config.llm.provider === 'claude') {
    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) throw new Error('ANTHROPIC_API_KEY is not set');
    const client = new Anthropic({ apiKey });

    const params: Record<string, unknown> = {
      model: config.llm.model,
      max_tokens: config.llm.max_tokens ?? 4096,
      messages: [{ role: 'user', content: prompt }],
    };

    if (config.llm.temperature !== undefined) {
      params.temperature = config.llm.temperature;
    }

    if (config.llm.thinking) {
      const budget = typeof config.llm.thinking === 'number' ? config.llm.thinking : 1600;
      params.thinking = { type: 'enabled', budget_tokens: budget };
      delete params.temperature;
    }

    const response = await client.messages.create(params as any);
    return (response.content[0] as { type: 'text'; text: string }).text;
  }

  if (config.llm.provider === 'openai') {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) throw new Error('OPENAI_API_KEY is not set');
    const client = new OpenAI({ apiKey });
    const params: Record<string, unknown> = {
      model: config.llm.model,
      messages: [{ role: 'user', content: prompt }],
      max_tokens: config.llm.max_tokens ?? 4096,
    };
    if (config.llm.temperature !== undefined) {
      params.temperature = config.llm.temperature;
    }
    const response = await client.chat.completions.create(params as any);
    return response.choices[0]?.message?.content ?? '';
  }

  // For deepseek and custom, use OpenAI-compatible API
  const apiKey =
    config.llm.provider === 'deepseek' ? process.env.DEEPSEEK_API_KEY : process.env.CUSTOM_API_KEY;
  if (!apiKey) throw new Error(`${config.llm.provider.toUpperCase()}_API_KEY is not set`);

  const baseURL =
    config.llm.provider === 'deepseek'
      ? 'https://api.deepseek.com/v1'
      : (config.llm.custom?.endpoint ?? 'https://api.openai.com/v1');
  const model =
    config.llm.provider === 'custom' ? (config.llm.custom?.model ?? config.llm.model) : config.llm.model;

  const client = new OpenAI({ apiKey, baseURL });
  const params: Record<string, unknown> = {
    model,
    messages: [{ role: 'user', content: prompt }],
    max_tokens: config.llm.max_tokens ?? 4096,
  };
  if (config.llm.temperature !== undefined) {
    params.temperature = config.llm.temperature;
  }
  const response = await client.chat.completions.create(params as any);
  return response.choices[0]?.message?.content ?? '';
}

async function handleReview(
  token: string,
  owner: string,
  repo: string,
  pullNumber: number,
  repoPath: string,
  config: ReturnType<typeof loadConfig>,
  event: Record<string, unknown>
): Promise<void> {
  // Load project context
  const contextResult = loadContext(repoPath, config);

  // Check if this is a first PR and no context file exists
  if (!contextResult.exists && event.pull_request) {
    const eventAction = (event as { action?: string }).action;
    if (eventAction === 'opened') {
      await postComment(
        token, owner, repo, pullNumber,
        `Hi! I'm PatchFox. I noticed this repo doesn't have a project context file (\`${contextResult.filename}\`).\n\n` +
        `A context file helps me understand your project's architecture, conventions, and guidelines, leading to much better code reviews.\n\n` +
        `**Reply with \`/review generate-context\`** and I'll analyze your entire project and generate one for you. ` +
        `You can then review and customize it.\n\n` +
        `> You can also create \`${contextResult.filename}\` manually at any time.`
      );
    }
  }

  console.log(`Reviewing PR #${pullNumber} in ${owner}/${repo} using ${config.llm.provider}`);

  const { diff, files, pr } = await fetchPRContext(token, owner, repo, pullNumber);

  if (!diff.trim()) {
    console.log('Empty diff. Skipping review.');
    process.exit(0);
  }

  const maxFiles = config.limits?.max_files ?? 20;
  const maxLines = config.limits?.max_lines_per_file ?? 500;

  let truncatedFiles = files.slice(0, maxFiles).map((f) => ({
    ...f,
    patch: f.patch
      ?.split('\n')
      .slice(0, maxLines)
      .join('\n'),
  }));

  let truncated = files.length > maxFiles;

  // Read full file contents for changed files (better context for LLM)
  const changedFilenames = truncatedFiles.map((f) => f.filename);
  const fullFileContents = readChangedFiles(repoPath, changedFilenames);

  const truncatedDiff = truncatedFiles
    .map((f) => `--- a/${f.filename}\n+++ b/${f.filename}\n${f.patch ?? ''}`)
    .join('\n');

  // Combine diff with full file contents for richer context
  const enhancedDiff = truncatedDiff + '\n\n## Full File Contents (for context)\n\n' + fullFileContents;

  const provider = createProvider(config.llm);
  const result = await provider.review({
    diff: enhancedDiff,
    files: truncatedFiles,
    pr,
    config: config.llm,
    context: contextResult.content,
  });

  let summary = result.summary;
  if (truncated) {
    summary += `\n\n_(Review truncated: only first ${maxFiles} files were reviewed.)_`;
  }
  if (contextResult.exists) {
    summary += `\n\n_(Review enhanced with project context from \`${contextResult.filename}\`.)_`;
  }

  const headSha = (event as { pull_request?: { head?: { sha?: string } } }).pull_request?.head?.sha;
  if (headSha) {
    await postReview(token, owner, repo, pullNumber, headSha, {
      ...result,
      summary,
    });
    console.log(`Review posted: ${result.comments.length} comments`);
  }
}

main();
